server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost/subbotnik
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: 'classpath:session_tables.sql'

security:
  oauth2:
    client:
      clientId: fd7e616d-1031-454e-be04-91e7ad2f949e
      clientSecret: ${CLIENT_SECRET}
      accessTokenUri: https://identity.akvelon.net:8454/connect/token
      userAuthorizationUri: https://identity.akvelon.net:8454/connect/authorize
      scope: openid, profile, email
    resource:
      userInfoUri: https://identity.akvelon.net:8454/connect/userinfo